apiVersion: v1
kind: Namespace
metadata:
  name: tomo-website-dev

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tomo-website-dev
  name: tomo-website
  labels:
    app: tomo-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomo-website
  template:
    metadata:
      labels:
        app: tomo-website
    spec:
      containers:
        - name: tomo-website
          image: 172.31.20.22:80/tomo-inc/tomo-website:dev
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "200Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
          securityContext:
            capabilities:
              add:
                - SYS_RESOURCE
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "ulimit -n 65535"]
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  namespace: tomo-website-dev
  name: tomo-website
spec:
  selector:
    app: tomo-website
  ports:
    - protocol: TCP
      port: 4321
      targetPort: 4321
  type: NodePort